export const ADD_EXPENSE = 'ADD_EXPENSE'
export const DELETE_EXPENSE = 'DELETE_EXPENSE'
export const EDIT_EXPENSE = 'EDIT_EXPENSE'
export const UPDATE_LIST_EXPENSE = 'UPDATE_LIST_EXPENSE'

export const UPDATE_FILTER = 'UPDATE_FILTERS'